export const txs = {
    'Burn TX (type 6 v3)  max value': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/IILUkL2mLygD0gYuCiwKILsM+xG+LXXAXKBEMaDQbxxmLmjFSL3h7wTdpTfz+YfTEP//////////fw==',
        'Json': {
            'id': '91r4RZ8ueJ4nasp9TKhLhyeQgqdE5dLSo4xpEeepk3CR',
            'type': 6,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'DbAik7g5NQcqTPPTiZnr97w4c6jjuahwjeDtTB7tJuQv',
            'amount': '9223372036854775807',
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236449794,
            'proofs': ['2jRDTypn5WVgrdxAQw4tF1VCbUidkuyumKMAM3y6wwYEiS75539tmhGiu18oDpAe2Sw5Gh7UeXW1bYbHr9aPi2sc'],
        },
    },
    'Burn TX (type 6 v3)  min value': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GINrUkL2mLygD0gYkCiIKILsM+xG+LXXAXKBEMaDQbxxmLmjFSL3h7wTdpTfz+YfT',
        'Json': {
            'id': 'Ea2ZTwwNmtnYuWwP26L8NrXxY23aTobYNpvSWFoHg5XN',
            'type': 6,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'DbAik7g5NQcqTPPTiZnr97w4c6jjuahwjeDtTB7tJuQv',
            'amount': 0,
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236449882,
            'proofs': ['2ew2iYLyyPf4B5n3i8guCxzGNrQimerLc4CLQGJPEqgZjNsA25E9CXJ5SmTum3uNBoV6u8br8t1FJ5mnRzT6Yr14'],
        },
    },
    'Cancel Lease TX (type 9 v3) ': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/ILHZkL2mLygD6gYiCiCe+fMMzlYhQXls5wGSZq+PaavsNCSexQH8Pe9VkvPcqQ==',
        'Json': {
            'id': '5ERaApUbL9o7oX1Vg9yoXJgRsRnMp37yDTtbcaD4csLN',
            'type': 9,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'leaseId': 'BhaURR89tjeVWq1xnt4qLjQvYAGnmmocDmvnb1hooR1z',
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236450481,
            'proofs': ['a63AFSP1oxMNrkRPXfiTcVRFeB3vYjJyKzTqQdHrK8rdh34397rnbQtXFExgsqvniFCmvXFKqcpeXirLJEyPoYw'],
        },
    },
    'Create Alias TX (type 10 v3)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/IOfekL2mLygD8gYgCh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18=',
        'Json': {
            'id': '7CA3At6BcTNF68cRGuKhHqGzBubSRe9MK1iF9Jejp1En',
            'type': 10,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'alias': '_rich-account.with@30_symbols_',
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236451175,
            'proofs': ['ZQxN8M6ryeYvfWsBRssbeeu8bXMpuLJYkRCwFJxYe4K8anogcbiRBDX9crRReus7mABGwogSMQdn1vxd9EAmQb4'],
        },
    },
    'Create Alias TX (type 10 v3)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIOzekL2mLygD8gYGCgRfbWlu',
        'Json': {
            'id': '7zDKtrEidtEHGndTv1mJT9twycsscTdHe5qHaFcsbiWq',
            'type': 10,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'alias': '_min',
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236451180,
            'proofs': ['oJ2gUyF28hFE2Q1BXaSJgoe3QunNcSMYbbgpApjow7SX1c8XTXNJj4wwATDCyZLho4CFvbgMQjnHv7AAkJcvXm2'],
        },
    },
    'DataTransaction TX (type 12 v2)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/IKrkkL2mLygCggdNCggKBGJvb2xYAQoPCgNpbnRQ//////////9/ChIKA2JpbmILc29tZSBzdHJpbmcKEgoDc3Ryagtzb21lIHN0cmluZwoICgZkZWxLZXk=',
        'Json': {
            'id': '8zNFqEUxXeRRpjhQDSrC52WvAxEi5NgMnPzNySuYtXEc',
            'type': 12,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'data': [{'key': 'bool', 'type': 'boolean', 'value': true}, {
                'key': 'int',
                'type': 'integer',
                'value': '9223372036854775807',
            }, {'key': 'bin', 'type': 'binary', 'value': 'base64:c29tZSBzdHJpbmc='}, {
                'key': 'str',
                'type': 'string',
                'value': 'some string',
            }, {'key': 'delKey', 'value': null}],
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236451882,
            'proofs': ['2B6E8MV51MqKqXdmXPqpizNfAkrQCzt14KSkYk4U2LJ7ATqygwkmcmeh4NP3YPVWK3ZXRevQefcWgMSnYJHadZWC'],
        },
    },
    'DataTransaction TX (type 12 v2)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GILTkkL2mLygCggdNCggKBGJvb2xYAQoPCgNpbnRQ//////////9/ChIKA2JpbmILc29tZSBzdHJpbmcKEgoDc3Ryagtzb21lIHN0cmluZwoICgZkZWxLZXk=',
        'Json': {
            'id': 'GpwCuzi75RtsANwL514f3LHEXeoY8FdtScca48uFYTs9',
            'type': 12,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'data': [{'key': 'bool', 'type': 'boolean', 'value': true}, {
                'key': 'int',
                'type': 'integer',
                'value': '9223372036854775807',
            }, {'key': 'bin', 'type': 'binary', 'value': 'base64:c29tZSBzdHJpbmc='}, {
                'key': 'str',
                'type': 'string',
                'value': 'some string',
            }, {'key': 'delKey', 'value': null}],
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236451892,
            'proofs': ['3wabyy2vXWDe79oPpnbYZ5RFHpsCvsz6EbuFUSjpaf4PGjU6CBPQE5rpyfjoMH6ur3RdztcDLAfq8cmTt5qubS9j'],
        },
    },
    'InvokeScript TX (type 16 v2)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoMIeIPTlkL2mLygCogcbChYKFMCJgEpQH4BNVdKzU7jR4jDzcS12EgEA',
        'Json': {
            'id': '2tCkJaF4pwcb4WGypPXoPHqfZnP88eQNyiC5UcrZznHf',
            'type': 16,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'dApp': '3N7U8EVrPNXRp4rQ6LNebhmjqzA4gPY641Q',
            'payment': [],
            'fee': 500000,
            'feeAssetId': null,
            'timestamp': 1625236452084,
            'proofs': ['2GEDViputWwT9zA2do5rU1ErhYMubtpka78D5LFx7Uqqo2t91rCve4jzVKZtZN4eGpPkBSXyyaJmD6A4jVoDPjfE'],
        },
    },
    'InvokeScript TX (type 16 v2)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGiwKIMoaglOigu8JmH4V0CybQhURZvAmnXAhYMYSGV4ZSfbrEP//////////fyD95ZC9pi8oAqIHVgoWChTAiYBKUB+ATVXSs1O40eIw83EtdhISAQkBAAAAB2RlZmF1bHQAAAAAGgIQChokCiDKGoJTooLvCZh+FdAsm0IVEWbwJp1wIWDGEhleGUn26xAU',
        'Json': {
            'id': 'EAFs6Mv92VsvFnxgrHnZQ9qbxPsCukdSsmnZ39kBBhgK',
            'type': 16,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'dApp': '3N7U8EVrPNXRp4rQ6LNebhmjqzA4gPY641Q',
            'call': {'function': 'default', 'args': []},
            'payment': [{'amount': 10, 'assetId': null}, {
                'amount': 20,
                'assetId': 'EbvoPG191bVa2HfMGoRAJyeysHQbTDLDMadtSfCmSggJ',
            }],
            'fee': '9223372036854775807',
            'feeAssetId': 'EbvoPG191bVa2HfMGoRAJyeysHQbTDLDMadtSfCmSggJ',
            'timestamp': 1625236452093,
            'proofs': ['57bggAeTpEzjf5d5Lcuc8bKo5NH3bzKtUG2CJZCE4w2HcNoY4DncAMmvVGfc5aMz5Unoa6KxKPv3TYjUo99N71rs'],
        },
    },
    'InvokeScript TX (type 16 v2)  case 3': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoMIeIP/lkL2mLygCogeIAQoWChTAiYBKUB+ATVXSs1O40eIw83EtdhJIAQkBAAAADnRlc3RGdW5jdGlvblYyAAAABwYHAQAAAAZhYWFhYWEAf/////////8AAAAAAAAAAAACAAAABmFhYWFhYQIAAAAAGiQKIMoaglOigu8JmH4V0CybQhURZvAmnXAhYMYSGV4ZSfbrEBQ=',
        'Json': {
            'id': '6gNfvezEjEwNnVZRBzuPLDky74Nf7i5t1KH58KQY4Jgx',
            'type': 16,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'dApp': '3N7U8EVrPNXRp4rQ6LNebhmjqzA4gPY641Q',
            'call': {
                'function': 'testFunctionV2',
                'args': [
                    {'type': 'boolean', 'value': true},
                    {'type': 'boolean', 'value': false},
                    {'type': 'binary', 'value': 'base64:YWFhYWFh'},
                    {'type': 'integer', 'value': '9223372036854775807'},
                    {'type': 'integer', 'value': 0},
                    {'type': 'string', 'value': 'aaaaaa'},
                    {'type': 'string', 'value': ''},
                ],
            },
            'payment': [{'amount': 20, 'assetId': 'EbvoPG191bVa2HfMGoRAJyeysHQbTDLDMadtSfCmSggJ'}],
            'fee': 500000,
            'feeAssetId': null,
            'timestamp': 1625236452095,
            'proofs': ['4YZWF78DugAmmRyAv75JEGQ6jB2tLzqYozh13iTkWY73ARvEANBUM27TjvuYQ2A9au7nycUNJEuoRMjvhKkRecun'],
        },
    },
    'InvokeScript TX (type 16 v2)  case 4': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoMIeIIDmkL2mLygCogeWAQoWChTAiYBKUB+ATVXSs1O40eIw83EtdhJ8AQkBAAAADnRlc3RGdW5jdGlvblYyAAAACAYHAQAAAAZhYWFhYWEAf/////////8AAAAAAAAAAAACAAAABmFhYWFhYQIAAAAACwAAAAcGBwEAAAAGYWFhYWFhAH//////////AAAAAAAAAAAAAgAAAAZhYWFhYWECAAAAAA==',
        'Json': {
            'id': '8Lnpz9rwXiEkLNptkVb2HRQsEM3KdSSqTSAi1B2fDirJ',
            'type': 16,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'dApp': '3N7U8EVrPNXRp4rQ6LNebhmjqzA4gPY641Q',
            'call': {
                'function': 'testFunctionV2',
                'args': [{'type': 'boolean', 'value': true}, {'type': 'boolean', 'value': false}, {
                    'type': 'binary',
                    'value': 'base64:YWFhYWFh',
                }, {'type': 'integer', 'value': '9223372036854775807'}, {
                    'type': 'integer',
                    'value': 0,
                }, {'type': 'string', 'value': 'aaaaaa'}, {'type': 'string', 'value': ''}, {
                    'type': 'list',
                    'value': [{'type': 'boolean', 'value': true}, {
                        'type': 'boolean',
                        'value': false,
                    }, {'type': 'binary', 'value': 'base64:YWFhYWFh'}, {
                        'type': 'integer',
                        'value': '9223372036854775807',
                    }, {'type': 'integer', 'value': 0}, {'type': 'string', 'value': 'aaaaaa'}, {
                        'type': 'string',
                        'value': '',
                    }],
                }],
            },
            'payment': [],
            'fee': 500000,
            'feeAssetId': null,
            'timestamp': 1625236452096,
            'proofs': ['rGSSy6kSyfQKqZspWgjHGavKuaEjE5zncdciKMGjZ78cvuXLaDBNejUu6FUwc7pUQczn4HryHENTB6iZCiR9qHG'],
        },
    },
    'InvokeScript TX (type 16 v2)  case 5': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoMIeIIHmkL2mLygCoge+AQoWChTAiYBKUB+ATVXSs1O40eIw83EtdhJ8AQkBAAAADnRlc3RGdW5jdGlvblYyAAAACAYHAQAAAAZhYWFhYWEAf/////////8AAAAAAAAAAAACAAAABmFhYWFhYQIAAAAACwAAAAcGBwEAAAAGYWFhYWFhAH//////////AAAAAAAAAAAAAgAAAAZhYWFhYWECAAAAABoCEAEaAhACGgIQAxoCEAQaAhAFGgIQBhoCEAcaAhAIGgIQCRoCEAo=',
        'Json': {
            'id': 'D3DnfGkCTu4mpruDY6wmBx2kyN1y3Rzrjhcc2GQoWfM2',
            'type': 16,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'dApp': '3N7U8EVrPNXRp4rQ6LNebhmjqzA4gPY641Q',
            'call': {
                'function': 'testFunctionV2',
                'args': [{'type': 'boolean', 'value': true}, {'type': 'boolean', 'value': false}, {
                    'type': 'binary',
                    'value': 'base64:YWFhYWFh',
                }, {'type': 'integer', 'value': '9223372036854775807'}, {
                    'type': 'integer',
                    'value': 0,
                }, {'type': 'string', 'value': 'aaaaaa'}, {'type': 'string', 'value': ''}, {
                    'type': 'list',
                    'value': [{'type': 'boolean', 'value': true}, {
                        'type': 'boolean',
                        'value': false,
                    }, {'type': 'binary', 'value': 'base64:YWFhYWFh'}, {
                        'type': 'integer',
                        'value': '9223372036854775807',
                    }, {'type': 'integer', 'value': 0}, {'type': 'string', 'value': 'aaaaaa'}, {
                        'type': 'string',
                        'value': '',
                    }],
                }],
            },
            'payment': [{'amount': 1, 'assetId': null}, {'amount': 2, 'assetId': null}, {
                'amount': 3,
                'assetId': null,
            }, {'amount': 4, 'assetId': null}, {'amount': 5, 'assetId': null}, {
                'amount': 6,
                'assetId': null,
            }, {'amount': 7, 'assetId': null}, {'amount': 8, 'assetId': null}, {
                'amount': 9,
                'assetId': null,
            }, {'amount': 10, 'assetId': null}],
            'fee': 500000,
            'feeAssetId': null,
            'timestamp': 1625236452097,
            'proofs': ['2RfTMxn8U9KYB3FRKyGNXRp5mbNCPutXi4HpF43ZnNEmMDfLiv68YsJyKodaD1akVHX8KEtKb7C6U1vsjhAeDChP'],
        },
    },
    'Issue TX (type 3 v3)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgUQgMLXLyC655C9pi8oA7oGEgoEYWFhYRj//////////38oAQ==',
        'Json': {
            'id': 'AgZuUkFBW8nQLmSroaofQM7fKndZcJh8L8jDjeRiBVhp',
            'type': 3,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'name': 'aaaa',
            'description': '',
            'quantity': '9223372036854775807',
            'decimals': 0,
            'reissuable': true,
            'script': null,
            'fee': 100000000,
            'feeAssetId': null,
            'timestamp': 1625236452282,
            'proofs': ['5d3rL3CqRKKTMeFtqQyYjQwrDKWmSsjjyASYT71maduowj9YD8C4Fbuaz3ebizimGrKyzL89WNYxu8HJkRfLcjMh'],
        },
    },
    'Issue TX (type 3 v3)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/IL7nkL2mLygDugaDCAoQYWFhYWFhYWFhYWFhYWFhYRLoB2FhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWEYh61LIAc=',
        'Json': {
            'id': '9ykibBy4yQMMg9jJtot9HXEgVfijYRHTyCdNuYdSKtGy',
            'type': 3,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'name': 'aaaaaaaaaaaaaaaa',
            'description': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
            'quantity': 1234567,
            'decimals': 7,
            'reissuable': false,
            'script': null,
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236452286,
            'proofs': ['3DCJoduExFdnPe5hDoawXDMUvpVV75116XaTRi2HQW5YTk1cATqEANUkqUh3j6gMpvaGFAZFCQfN8uuNtDZMDVuo'],
        },
    },
    'Issue TX (type 3 v3)  case 3': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgUQgMLXLyDA55C9pi8oA7oGOgoQYWFhYWFhYWFhYWFhYWFhYRIYU29tZSBhc3NldCAKIGRlc2NyaXB0aW9uGP//////////fyAIKAE=',
        'Json': {
            'id': '4eYYdXtF1HkKZJ43p7GuLeeJazLj2drPmLdCP3YxpUBQ',
            'type': 3,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'name': 'aaaaaaaaaaaaaaaa',
            'description': 'Some asset \n description',
            'quantity': '9223372036854775807',
            'decimals': 8,
            'reissuable': true,
            'script': null,
            'fee': 100000000,
            'feeAssetId': null,
            'timestamp': 1625236452288,
            'proofs': ['5vuA9JiCe7k1tNAdnTiEGfZZC4sSNA1skD9nc36TvyCLiqsH6mg63BdgwTz7AnPfbEbpoukuu7HvfTUPuxhXn6rG'],
        },
    },
    'Issue TX (type 3 v3)  case 4': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgUQgMLXLyCo6JC9pi8oA7oGjwgKEGFhYWFhYWFhYWFhYWFhYWES6AdhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhGP//////////fzIGBQbtKNoM',
        'Json': {
            'id': '5g6QNvSkU9UvtLTsDeY7C6JpaqLzUxH8qZ1wg1UVS7V3',
            'type': 3,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'name': 'aaaaaaaaaaaaaaaa',
            'description': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
            'quantity': '9223372036854775807',
            'decimals': 0,
            'reissuable': false,
            'script': 'base64:BQbtKNoM',
            'fee': 100000000,
            'feeAssetId': null,
            'timestamp': 1625236452392,
            'proofs': ['5Af6EvNh1Ns3B9o4zZXUHuYV4b7CUgFkbdAcvx4zjyEfxt1EcRdTEp7oDepVnfjqLZ6L97ERC3wxRVC56kwjWvDm'],
        },
    },
    'Lease TX (type 8 v3) case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/IOLpkL2mLygD4gYiChYKFFcIkVxjWTvmPEJhGqt/lw3DCksGEP//////////fw==',
        'Json': {
            'id': '5CXhJmYDRV9tWVepHCv8JrYEW9WjNn51bZMFjZ9xe1A3',
            'type': 8,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'recipient': '3MwrGpurVChT8VtveXSfzBBr1VSfSMWTzHC',
            'amount': '9223372036854775807',
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236452578,
            'proofs': ['42zY1Xv149pzfzBEE3k35jGZXcZnJcxX8ciXQK5x5EoVpDxYzESx9QwoA4NteSZ1yiZS8SLdpiiNn8pqydhfcoAf'],
        },
    },
    'Lease TX (type 8 v3) case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIOXpkL2mLygD4gYsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38=',
        'Json': {
            'id': '454FBtg5qqPiNgoQGPgtndszeB3BCwquYiabpsuAvPQf',
            'type': 8,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'recipient': 'alias:T:_rich-account.with@30_symbols_',
            'amount': '9223372036854775807',
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236452581,
            'proofs': ['2xmfRE666JdWuakVhPcbhAh92t9LXScbniRCcPNhBR5LzESnYBEksNySg7sJCc99qqkYD4z1avsjWq8B9PoKvaKg'],
        },
    },
    'Lease TX (type 8 v3) case 3': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIObpkL2mLygD4gYKCgYSBF9taW4QAQ==',
        'Json': {
            'id': 'EtsPoocJQuemHKyMsLhrsdzYHGXV6WcXSqH43FZwtZUa',
            'type': 8,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'recipient': 'alias:T:_min',
            'amount': 1,
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236452582,
            'proofs': ['383Vzd66b5n8KkELzACP7DZfuHyCyJrWCpx4ibUNSjh1emAWTfTaTQoCLkag7PxabHFqgsWcm1THGHVna2bWTTEF'],
        },
    },
    'MassTransfer TX (type 11 v2)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/IKLrkL2mLygC+gZDEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4aCXR0dHR0dHR0dA==',
        'Json': {
            'id': 'ApxpgfSeBEsUHs6AVksm7KnEhSqu1P2dR619zb2a3k8N',
            'type': 11,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': null,
            'attachment': '2UyXA7eLNfqs1',
            'transfers': [{
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}],
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236452770,
            'proofs': ['ZkEaypNo8DHQb6daLUD2x7skQnbctu45mM46cu85aNijEYgNe3Lau3koYM2Yg2JQcyhgiyncUasM2ai9uRyD6Ln'],
        },
    },
    'MassTransfer TX (type 11 v2)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQwJoMIKnrkL2mLygC+gZgCiBMFts28xXe6DugIz4tWNcHbE9xn9MVWp7aMU46y+Yb4RIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjj',
        'Json': {
            'id': 'E9HMvT2kik8KZbFxBjKUhsFWM89BDDuPgTbxwWdYxb4H',
            'type': 11,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': '682CZKmF8DH4zypt1hEsksL8xTsPUw1i1T51DhXZHVWY',
            'attachment': '',
            'transfers': [{
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM', 'amount': 0}],
            'fee': 200000,
            'feeAssetId': null,
            'timestamp': 1625236452777,
            'proofs': ['4nBHSwsD3GX9QWQF7oGE82dPgcKK1JAFTbkAKx4H7LxHkainPVsasWztWsQSBjY7SfaLvRkhjiHPdV71G5wUTTSx'],
        },
    },
    'MassTransfer TX (type 11 v2)  case 3': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQwJoMIN+Wg8GmLygC+gZSCiBMFts28xXe6DugIz4tWNcHbE9xn9MVWp7aMU46y+Yb4RIiChYKFJoNq5sJ8GKR5Xi6i06We0UDBHnCEP//////////fxIKCgYSBF9taW4QAQ==',
        'Json': {
            'id': '458imqLJLoioqBxp1jTzMytfsNkiANpSm3qfCowMET13',
            'type': 11,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': '682CZKmF8DH4zypt1hEsksL8xTsPUw1i1T51DhXZHVWY',
            'transfers': [{
                'recipient': '3N3xeDHzzC16aoj9jtbo6ZL69VWtYSqJs4M',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:W:_min', 'amount': 1}],
            'fee': 200000,
            'feeAssetId': null,
            'timestamp': 1625244617567,
            'proofs': ['4Wgx72Kq5vs9BNxBEb6pGN8xApr8rkR4emQvVbLrPYWAewWRZDrTuyfDf5hV2yBp77vuWerx7NEcrw2pQ1Q8WhY7'],
        },
    },
    'MassTransfer TX (type 11 v2)  case 4': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgUQ4KO3AiCq65C9pi8oAvoGqBcKIEwW2zbzFd7oO6AjPi1Y1wdsT3Gf0xVantoxTjrL5hvhEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4xIsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38SCAoGEgRfbWluEiIKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMQ//////////9/EhgKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMSLAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18Q//////////9/EggKBhIEX21pbhIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4xIsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38SCAoGEgRfbWluEiIKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMQ//////////9/EhgKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMSLAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18Q//////////9/EggKBhIEX21pbhIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4xIsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38SCAoGEgRfbWluEiIKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMQ//////////9/EhgKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMSLAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18Q//////////9/EggKBhIEX21pbhIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4xIsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38SCAoGEgRfbWluEiIKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMQ//////////9/EhgKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMSLAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18Q//////////9/EggKBhIEX21pbhIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4xIsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38SCAoGEgRfbWluEiIKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMQ//////////9/EhgKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMSLAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18Q//////////9/EggKBhIEX21pbhIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4xIsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38SCAoGEgRfbWluEiIKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMQ//////////9/EhgKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMSLAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18Q//////////9/EggKBhIEX21pbhIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4xIsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38SCAoGEgRfbWluEiIKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMQ//////////9/EhgKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMSLAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18Q//////////9/EggKBhIEX21pbhIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4xIsCiASHl9yaWNoLWFjY291bnQud2l0aEAzMF9zeW1ib2xzXxD//////////38SCAoGEgRfbWluEiIKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMQ//////////9/EhgKFgoU/YWTXMKdFOIaL3tq7WuGm9BVKOMSLAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18Q//////////9/EggKBhIEX21pbhIiChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEP//////////fxIYChYKFP2Fk1zCnRTiGi97au1rhpvQVSjjEiwKIBIeX3JpY2gtYWNjb3VudC53aXRoQDMwX3N5bWJvbHNfEP//////////fxIICgYSBF9taW4SIgoWChT9hZNcwp0U4hove2rta4ab0FUo4xD//////////38SGAoWChT9hZNcwp0U4hove2rta4ab0FUo4w==',
        'Json': {
            'id': '2hp9KK7WfazDJ1y4Ruyd6TuMKX8jEBQmvQcFDagabFBK',
            'type': 11,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': '682CZKmF8DH4zypt1hEsksL8xTsPUw1i1T51DhXZHVWY',
            'attachment': '',
            'transfers': [{
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': 0,
            }, {
                'recipient': 'alias:T:_rich-account.with@30_symbols_',
                'amount': '9223372036854775807',
            }, {'recipient': 'alias:T:_min', 'amount': 0}, {
                'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM',
                'amount': '9223372036854775807',
            }, {'recipient': '3ND2akT8nQH3BDWFWe4Jak4sTVYpzCQs1aM', 'amount': 0}],
            'fee': 5100000,
            'feeAssetId': null,
            'timestamp': 1625236452778,
            'proofs': ['3TgFHSewBjYGZFJ8GZi6bj3u9VJLGLgu4kYwy78Gy7Mo3sfyr4Rv8ABZ8ksiu1Bk9Z5TFga6v5UUyfWdPpVdaBGD'],
        },
    },
    'Reissue TX (type 5 v3)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/IObskL2mLygDygYuCiwKILsM+xG+LXXAXKBEMaDQbxxmLmjFSL3h7wTdpTfz+YfTEP//////////fw==',
        'Json': {
            'id': '6gWMT9HJy2RMRKpUmJgNvHsi37Njd9U4VA2BMv2Szjrj',
            'type': 5,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'DbAik7g5NQcqTPPTiZnr97w4c6jjuahwjeDtTB7tJuQv',
            'quantity': '9223372036854775807',
            'reissuable': false,
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236452966,
            'proofs': ['37CFrkNoujidUTxAmrEVBqjTFUQwfBusv2ajuo9BqjCHSg8WZzYDwVHdEwSJN8wBs813fyodqk2Xsr5wgsVm9sgh'],
        },
    },
    'Reissue TX (type 5 v3)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIOrskL2mLygDygYmCiIKILsM+xG+LXXAXKBEMaDQbxxmLmjFSL3h7wTdpTfz+YfTEAE=',
        'Json': {
            'id': 'pzXgBkiL4uSuUgcvF3dy7vcXDYxVeRRLFUKdEMvnPEQ',
            'type': 5,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'DbAik7g5NQcqTPPTiZnr97w4c6jjuahwjeDtTB7tJuQv',
            'quantity': 0,
            'reissuable': true,
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236452970,
            'proofs': ['28FGxpaUG8jCxhZtwKc6tsFgLA3tkRAvjLZMKJR8HK6KfpmYTK2AnJF66BAvRdMYhgDYzFdsobn3JqDySMRLuwvd'],
        },
    },
    'SetAssetScriptTx (type 15 v2)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgUQgMLXLyCi7pC9pi8oApoHKgogwkoWDCcBbsGA9lONNps+7njcvr8W9YwxrrjLKquI23gSBgMGXdHGHw==',
        'Json': {
            'id': 'DLR9mzo1bD1xcoGXHqB2TpoZVL5S7Ek7MzTr74zMzekW',
            'type': 15,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'E5Rcha533YfMJZE9aDmx2m5tZSYYt6HWgFU3jkP4YGDV',
            'script': 'base64:AwZd0cYf',
            'fee': 100000000,
            'feeAssetId': null,
            'timestamp': 1625236453154,
            'proofs': ['mYCdyGNyccccsekoaJ4km8Z6DyJGTWsYo8CLvhN553gr7JzM6QNCze2EqWgAy8WMoJpyHMdACzfb1G7VX2s7FFo'],
        },
    },
    'SetAssetScriptTx (type 15 v2)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgoQ//////////9/IKbukL2mLygCmgcqCiDCShYMJwFuwYD2U402mz7ueNy+vxb1jDGuuMsqq4jbeBIGAwZd0cYf',
        'Json': {
            'id': '8osbcSuTnqMW7TYdxXS5FmPQZJanC5vvRcudXoguZMmH',
            'type': 15,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'E5Rcha533YfMJZE9aDmx2m5tZSYYt6HWgFU3jkP4YGDV',
            'script': 'base64:AwZd0cYf',
            'fee': '9223372036854775807',
            'feeAssetId': null,
            'timestamp': 1625236453158,
            'proofs': ['2Fj18Ln7r3EmhtSNVSDrsqAG6BHYfYMTMpFhMeq2qc6oxpj4XWJmdmFxVcyBCmxMWCaf659ss1trsgW9DoYrU879'],
        },
    },
    'SetScript TX (type 13 v2)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQwIQ9IPDvkL2mLygCigcICgYDBl3Rxh8=',
        'Json': {
            'id': '4PoYSvgeFT5qEkXNM5UHqdridfbfDnrfR9tuajrvrXwq',
            'type': 13,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'script': 'base64:AwZd0cYf',
            'fee': 1000000,
            'feeAssetId': null,
            'timestamp': 1625236453360,
            'proofs': ['52mRVSS6Mg5L1xmRCkvES9HSCq5pQWciuPVF5ckVyw8YR2qvjqbFKxqHw9NaHypQW1F81zUp49x3fo3Z4UCdsxaf'],
        },
    },
    'SetScript TX (type 13 v2)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQwIQ9IPTvkL2mLygCigcA',
        'Json': {
            'id': 'DqKx9Koj1puaFhAbma26bEc9Bdx74RYk4Avmttt2JPmj',
            'type': 13,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'script': null,
            'fee': 1000000,
            'feeAssetId': null,
            'timestamp': 1625236453364,
            'proofs': ['4uBsLpxZwbopeWQk2uPUdbBZQvqhcTiru9G5HsMfa3R3Ym9iQFYGHhj45DFcinpyNDxMUyGzCVamqxWUex2CLRRi'],
        },
    },
    'SponsorFee TX (type 14 v2)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIKjxkL2mLygCkgcuCiwKIOQt6VHG7an7FIw6Rvt44jtBL/LIHaogX6oHdthqs7EgEP//////////fw==',
        'Json': {
            'id': 'A8Ht1dxzF831Np323RQVHhLXswwcEHGHr8mLgixPZQRs',
            'type': 14,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'GMiZSiRUd2kWrc2PDVWGGE2bB219wp2CHCBUipeJkvVm',
            'minSponsoredAssetFee': '9223372036854775807',
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236453544,
            'proofs': ['5pxTMmDPuJ8ARSATTKcDcTMXHHESdnfPZv6Q3XNVWi4xsvUHeJuVA4SmHnUBGEzmpMqupsJuWou6hVqvD1iwQwLJ'],
        },
    },
    'SponsorFee TX (type 14 v2)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGiwKIMoaglOigu8JmH4V0CybQhURZvAmnXAhYMYSGV4ZSfbrEP//////////fyCs8ZC9pi8oApIHJAoiCiDKGoJTooLvCZh+FdAsm0IVEWbwJp1wIWDGEhleGUn26w==',
        'Json': {
            'id': 'FsJVMQiBS1w9m7JTYBnL17kiDR9t8uSP3mJRrQ8pt1xk',
            'type': 14,
            'version': 2,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'EbvoPG191bVa2HfMGoRAJyeysHQbTDLDMadtSfCmSggJ',
            'minSponsoredAssetFee': 0,
            'fee': '9223372036854775807',
            'feeAssetId': 'EbvoPG191bVa2HfMGoRAJyeysHQbTDLDMadtSfCmSggJ',
            'timestamp': 1625236453548,
            'proofs': ['2TaSK17Gg9MsQmRAatgoDdEqvzWQ8Agi5WMR5JKK7rHLQnyX629dZ3dxbU38PjuDVUXQV4iYpk7miRCdnF4qJwe5'],
        },
    },
    'Transfer TX (type 4 v3)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGiwKIJRjWHGOPhB+jKCoAQaVBkscvc4D3bVoyGe0prXCZPi8EP//////////fyDn8pC9pi8oA8IGUAogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18SLAoglGNYcY4+EH6MoKgBBpUGSxy9zgPdtWjIZ7SmtcJk+LwQ//////////9/',
        'Json': {
            'id': '9mEqEeqfstsMEidu7VedNPzUkPnCPyBU8T4jZt1Dhrep',
            'type': 4,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'recipient': 'alias:T:_rich-account.with@30_symbols_',
            'amount': '9223372036854775807',
            'assetId': 'AzFCetMjPhAv4gjdnYzWsoEesyAdAB26kK81DU8yjMb9',
            'attachment': '',
            'fee': '9223372036854775807',
            'feeAssetId': 'AzFCetMjPhAv4gjdnYzWsoEesyAdAB26kK81DU8yjMb9',
            'timestamp': 1625236453735,
            'proofs': ['2F3Q1rGAu1wMRpcBwqPTUv5VTLSpMK3Xnih53WbtNYeYsN4h7qYLA44mu2MazvTo4ojijcC3EyXmg78XjAx81q8Y'],
        },
    },
    'Transfer TX (type 4 v3)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGiwKIJRjWHGOPhB+jKCoAQaVBkscvc4D3bVoyGe0prXCZPi8EP//////////fyDs8pC9pi8oA8IGJAoWChS9dlzzmCRnWwR2WyBD11RL65Az6hIKEP//////////fw==',
        'Json': {
            'id': 'DAEipw4VBRw1MRj8GhHZea6HcAeBo8Sk7kfCLKQKn73j',
            'type': 4,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'recipient': '3N7BsHBsgbYQU7aiDmpdiQ93GsPQBkzffLF',
            'amount': '9223372036854775807',
            'assetId': null,
            'attachment': '',
            'fee': '9223372036854775807',
            'feeAssetId': 'AzFCetMjPhAv4gjdnYzWsoEesyAdAB26kK81DU8yjMb9',
            'timestamp': 1625236453740,
            'proofs': ['34G24GV8kDgPGsiRyu6oP2bA11QjwM2LGiLXqwKvJntEuxjXA9uYF5oVXcZ7R3EpwT5C3rCHJKrXWyvqtNgYEKuU'],
        },
    },
    'Transfer TX (type 4 v3)  case 3': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIOzykL2mLygDwgbUAQogEh5fcmljaC1hY2NvdW50LndpdGhAMzBfc3ltYm9sc18SIgoglGNYcY4+EH6MoKgBBpUGSxy9zgPdtWjIZ7SmtcJk+LwaiwFUaGlzIGlzIDE0MCBieXRlcyBzdHJpbmcuVGhpcyBpcyAxNDAgYnl0ZXMgc3RyaW5nLlRoaXMgaXMgMTQwIGJ5dGVzIHN0cmluZy4gVGhpcyBpcyAxNDAgYnl0ZXMgc3RyaW5nLiBUaGlzIGlzIDE0MCBieXRlcyBzdHJpbmcuIFRoaXMgaXMgMTQw',
        'Json': {
            'id': 'HG4tyKjseHfeLAiMcYhi3g6Y5n3fkavcmyEWMVXn4xBA',
            'type': 4,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'recipient': 'alias:T:_rich-account.with@30_symbols_',
            'amount': 0,
            'assetId': 'AzFCetMjPhAv4gjdnYzWsoEesyAdAB26kK81DU8yjMb9',
            'attachment': 'ATKefavTrt8tt1b1Svjb5gDypuKh3qKaLM98Ps7bo1b9J4PzwKwtsmcbXRgeS57j9sCUss3uaQ51qW3Kg86yiDgcMwAJb12fXd588yQWj6bVTaJjPBbiDASATi75MXXtEVzUWT8rU6NuNAv6BocHWZ6aDQbRQ2p8uYoinVALNMRK8seo8yJyQqoFLTPxqd',
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236453740,
            'proofs': ['35U1rUKgkJpC4GGukcLTogPWv349HeD469XM7zpipB57Y5U6haQBMLSdnfvHZQ32T57FiDUH6idKBWgdAvM6b8xt'],
        },
    },
    'Transfer TX (type 4 v3)  case 4': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIO3ykL2mLygDwgaYAQoGEgRfbWluEgAaiwFUaGlzIGlzIDE0MCBieXRlcyBzdHJpbmcuVGhpcyBpcyAxNDAgYnl0ZXMgc3RyaW5nLlRoaXMgaXMgMTQwIGJ5dGVzIHN0cmluZy4gVGhpcyBpcyAxNDAgYnl0ZXMgc3RyaW5nLiBUaGlzIGlzIDE0MCBieXRlcyBzdHJpbmcuIFRoaXMgaXMgMTQw',
        'Json': {
            'id': 'FMABEt9NGxirJRrMgdwBTWjyUKPYB7G8iFfD3zHnGnkb',
            'type': 4,
            'version': 3,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'recipient': 'alias:T:_min',
            'amount': 0,
            'assetId': null,
            'attachment': 'ATKefavTrt8tt1b1Svjb5gDypuKh3qKaLM98Ps7bo1b9J4PzwKwtsmcbXRgeS57j9sCUss3uaQ51qW3Kg86yiDgcMwAJb12fXd588yQWj6bVTaJjPBbiDASATi75MXXtEVzUWT8rU6NuNAv6BocHWZ6aDQbRQ2p8uYoinVALNMRK8seo8yJyQqoFLTPxqd',
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236453741,
            'proofs': ['3bQfv3Ghgk58wxSwTT6EJCZenyFocStW9QCZ9C8srkK1hvSabWTdK3zgS4PvKu1UDA5BP9GYjHwcxLj3TeMrBzhR'],
        },
    },
    'UpdateAssetInfo TX (type 17 v1)  case 1': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIKT0kL2mLygBqgcoCiCmD2m17pwNNl0VrDjxrM/QOUsMn3uKIxmo1gqbN4tjFxIEYWFhYQ==',
        'Json': {
            'id': 'GGByPfj6Yz2B3TzSXWWxUZtoshfY6iwcBarcbggPdHtS',
            'type': 17,
            'version': 1,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'CBEJvpsMfhT9qFxNYL5Efv1DwE3JJ4LUPX3hpPfvjU3x',
            'name': 'aaaa',
            'description': '',
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236453924,
            'proofs': ['3TQvLbm3SNyzdrBHyGRQVGiNv4siyQLdMKXKYtojqAzdahr6FqSRHCtijnCbuPrCWnoE4SFvnLrKgLyyCdqBDsGP'],
        },
    },
    'UpdateAssetInfo TX (type 17 v1)  case 2': {
        'Bytes': 'CFQSIJL4Cg7m8oV+sUn/3SQWcJnIDvBjXYh3TIjvckIJrSwvGgQQoI0GIKj0kL2mLygBqgefCAog5C3pUcbtqfsUjDpG+3jiO0Ev8sgdqiBfqgd22GqzsSASEGFhYWFhYWFhYWFhYWFhYWEa6AdhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh',
        'Json': {
            'id': '2ksQqxFX6vb1LgRozu7n2s2qqmgZ5AxfgkaN5SWXFKfu',
            'type': 17,
            'version': 1,
            'chainId': 84,
            'senderPublicKey': 'Athtgb7Zm9V6ExyAzAJM1mP57qNAW1A76TmzXdDZDjbt',
            'sender': '3N3kDDPYNbb3vzZRAPkgiR1R7YnLVtSrsiZ',
            'assetId': 'GMiZSiRUd2kWrc2PDVWGGE2bB219wp2CHCBUipeJkvVm',
            'name': 'aaaaaaaaaaaaaaaa',
            'description': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
            'fee': 100000,
            'feeAssetId': null,
            'timestamp': 1625236453928,
            'proofs': ['EssLERPRdr2U87iRaPmELffb9Hd2X8Qspyy5PDkvrt4tm6SaJbDzUL29anDnKVv8VEtdSUAgPbytGnubJnSVG62'],
        },
    },
}
